server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${host:localhost}:${port:5432}/${dbname:pgsg}
    username: ${username}
    password: "${password}"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  kafka:
    ssl:
      trust-store-location: file:/app/ssl/kafka.server.truststore.jks
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always   # prod에서는 never로 변경 후 DDL 직접 실행
    properties:
      org.quartz.scheduler.instanceName: ProductScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 10000
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
