server:
  port: 8083

spring:
  application:
    name: trade-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL:jdbc:postgresql://${DB_HOST:db}:5432/${DB_DATABASE:tradedb}}"
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
  kafka:
    consumer:
      group-id: trade-service

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://xn--vm-3ip-z01x226e:9411/api/v2/spans

logging:
  file:
    name: /logs/trade-service.log
