server:
  port: 8084

spring:
  application:
    name: chat-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:pgsg-db:5432/chat-db}
    username: ${DB_USERNAME:pgsg-user}
    password: ${DB_PASSWORD:pgsg-password-1234}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    open-in-view: false
    generate-ddl: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://34.47.69.9:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, refresh, prometheus

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${SERVER_IP:${HOSTNAME:localhost}}
    hostname: ${SERVER_IP:${HOSTNAME:localhost}}
    instance-id: ${SERVER_IP:${HOSTNAME:${spring.application.name}}}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://34.64.58.121:8761/eureka/,http://34.64.104.174:8761/eureka/}
